version: '3.8'

services:
  php:
    build: .
    volumes:
      - ./www:/var/www/html
      - ./apache:/etc/apache2/sites-available
    ports:
      - "8000:80"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
